#ifdef NDEBUG
#undef NDEBUG
#endif
#include "../hook.cpp"
#include <cassert>
#include <chrono>
#include <fstream>
#include <iostream>
#include <thread>

namespace {
std::string observed;
void* observedInstance = nullptr;
int observedLimit = 0;
bool observedSingleLine = false;
void CaptureCompile(void* instance, const char* text) {
    observedInstance = instance;
    observed = text;
}
void CaptureMeasure(void* instance, float* width, float* height,
                    const char* text, int limit, bool singleLine) {
    observedInstance = instance;
    observed = text;
    observedLimit = limit;
    observedSingleLine = singleLine;
    *width = 123.5f;
    *height = 17.0f;
}
}

int main(int argc, char** argv) {
    const std::string valid = R"({"meta":[null,1.5e-2,true],"translations":{"ABC":"中文测试","Emoji":"\ud83d\ude00","None":"无"}})";
    assert(ToolbagDictionary::Parse(valid, g_translations));
    assert(g_translations.at("Emoji") == "\xf0\x9f\x98\x80");
    for (const auto* bad : {
        R"({"translations":{"A":"甲","A":"乙"}})",
        R"({"translations":{"A":"甲",}})",
        R"({"translations":{"A":"甲"})",
        R"({"translations":{"A":"甲"}} garbage)",
        R"({"translations":{"A":"\ud800"}})",
        R"({"translations":{"A":"\uXXXX"}})",
        R"({"translations":{"A":"\q"}})",
        R"({"translations":{"A":"\u0000x"}})",
        R"({"translations":{"A\u0000B":"甲"}})",
        R"({"translations":{"A":3}})",
        R"({"translations":{},"translations":{"A":"甲"}})",
        R"({"translations":{"A":"甲"},"meta":01})",
        R"({"translations":{"A":"甲"},"meta":[true,]})"}) {
        assert(!ToolbagDictionary::Parse(bad, g_translations));
        assert(g_translations.at("ABC") == "中文测试");
    }
    assert(!ToolbagDictionary::Parse(std::string("\xff", 1), g_translations));
    assert(!ToolbagDictionary::Parse(std::string(64 * 1024 * 1024 + 1, ' '), g_translations));
    StringMap unicode;
    assert(ToolbagDictionary::Parse(R"({"translations":{"Multiline":"行一\n行二\t%s %1 {value}","Long":"汉字"},"nested":{"translations":{"Wrong":"不可加载"}}})", unicode));
    assert(unicode.at("Multiline") == "行一\n行二\t%s %1 {value}");
    assert(unicode.size() == 2 && !unicode.contains("Wrong"));
    char source[] = "ABC";
    assert(std::string(TranslateText(source)) == "中文测试");
    assert(std::string(source) == "ABC");
    assert(std::string(TranslateText(" None ")) == " None ");
    assert(std::string(TranslateText("C:\\ABC.tbscene")) == "C:\\ABC.tbscene");
    const char* stable = TranslateText("  ABC\t");
    assert(std::string(stable) == "  中文测试\t");
    std::vector<std::thread> workers;
    for (int n = 0; n < 4; ++n) workers.emplace_back([] {
        for (int i = 0; i < 10000; ++i) {
            assert(std::string(TranslateText("ABC")) == "中文测试");
            assert(std::string(TranslateText("  ABC\t")) == "  中文测试\t");
        }
    });
    for (auto& worker : workers) worker.join();
    assert(std::string(stable) == "  中文测试\t");
    g_originalFontCompile[0] = CaptureCompile;
    g_originalFontCompile[1] = CaptureCompile;
    g_originalFontMeasure = CaptureMeasure;
    void* instance = source;
    HookPrimaryFontCompile(instance, source);
    assert(observed == "中文测试" && observedInstance == instance);
    HookSecondaryFontCompile(instance, source);
    assert(observed == "中文测试");
    float width = 0, height = 0;
    HookFontMeasure(instance, &width, &height, source, 27, true);
    assert(observed == "中文测试" && width == 123.5f && height == 17.0f);
    assert(observedLimit == 27 && observedSingleLine && observedInstance == instance);
    assert(std::string(source) == "ABC");
    // Relocated RIP-relative instructions must retain their original target.
    BYTE* arena = static_cast<BYTE*>(VirtualAlloc(nullptr, 4096,
        MEM_RESERVE | MEM_COMMIT, PAGE_READWRITE));
    assert(arena);
    const BYTE code[] = {0x48, 0x8b, 0x05, 0x20, 0, 0, 0};
    memcpy(arena, code, sizeof(code));
    assert(CopyRelocatedInstructions(arena + 128, arena, sizeof(code)));
    int32_t displacement = 0;
    memcpy(&displacement, arena + 131, sizeof(displacement));
    assert(arena + 135 + displacement == arena + 39);
    VirtualFree(arena, 0, MEM_RELEASE);
    if (argc > 1) {
        std::ifstream file(argv[1], std::ios::binary);
        const std::string bytes((std::istreambuf_iterator<char>(file)), {});
        StringMap official;
        assert(ToolbagDictionary::Parse(bytes, official));
        std::cout << "Official dictionary entries: " << official.size() << '\n';
        if (argc > 2) {
            // Independently generated by Python's JSON decoder: compare every
            // UTF-8 key/value, not only the number of entries.
            std::ifstream corpus(argv[2], std::ios::binary);
            uint32_t count = 0;
            corpus.read(reinterpret_cast<char*>(&count), sizeof(count));
            assert(corpus && count == official.size());
            auto read = [&] {
                uint32_t length = 0;
                corpus.read(reinterpret_cast<char*>(&length), sizeof(length));
                assert(corpus && length < 64 * 1024 * 1024);
                std::string value(length, '\0');
                corpus.read(value.data(), length);
                assert(corpus);
                return value;
            };
            for (uint32_t i = 0; i < count; ++i) {
                const auto key = read();
                const auto value = read();
                assert(official.at(key) == value);
            }
            assert(corpus.peek() == std::char_traits<char>::eof());
            std::cout << "PASS: every official key/value matches independent JSON decoding\n";
        }
    }
    if (argc > 3) {
        // Map the installed image for read-only locator verification. Never
        // execute the host entry point or install hooks into this image.
        HMODULE host = LoadLibraryExA(argv[3], nullptr, DONT_RESOLVE_DLL_REFERENCES);
        assert(host);
        BYTE* base = reinterpret_cast<BYTE*>(host);
        BYTE* begin = nullptr;
        BYTE* end = nullptr;
        assert(ResolveCodeRange(base, begin, end));
        BYTE* table = ResolveVtableByName(base, ".?AVText@mset@@");
        assert(table);
        BYTE* draw = ResolveTextDrawMethod(table, begin, end);
        if (!draw) {
            std::cerr << "Text table RVA=" << std::hex << (table - base) << std::dec << '\n';
            for (size_t i = 0; i < 64; ++i) {
                BYTE* method = reinterpret_cast<BYTE**>(table)[i];
                if (!IsExecutableAddress(method, begin, end)) break;
                const auto methodScore = ScoreTextMethod(method, begin, end);
                std::cerr << "slot=" << i << " rva=" << std::hex << (method - base)
                          << std::dec << " compile=" << methodScore.compileTargets
                          << " measure=" << methodScore.measureTargets << '\n';
            }
        }
        assert(draw);
        const auto score = ScoreTextMethod(draw, begin, end);
        assert(score.compileTargets >= 1 && score.measureTargets == 1);
        std::cout << "PASS: mapped host font compile targets=" << score.compileTargets
                  << ", measurement targets=" << score.measureTargets << '\n';
        FreeLibrary(host);
    }
    const auto begin = std::chrono::steady_clock::now();
    for (int i = 0; i < 100000; ++i) {
        assert(TranslateText(source) != source);
        assert(TranslateText("Missing label") != nullptr);
    }
    std::cout << "Lookup 100000 hits + 100000 misses: "
              << std::chrono::duration_cast<std::chrono::microseconds>(
                     std::chrono::steady_clock::now() - begin).count() << " us\n";
    std::cout << "PASS: strict dictionary, stable concurrent lookup, source preservation, both compile hooks, font metrics ABI and relocation\n";
}
